# Generated by Django 4.2.4 on 2024-05-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment_photo_comment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='initial_bid',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
